fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
_welcome:
    pattern:  /
    defaults: { _controller: TohouriStoreBundle:Accueil:index }
    
TohouriStoreBundle:
    resource: "@TohouriStoreBundle/Resources/config/routing.yml"
    prefix:   /