parameters:
#    tohouri_upload.example.class: Tohouri\UploadBundle\Example

services:
#    tohouri_upload.example:
#        class: %tohouri_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
