parameters:
#    tohouri_store.example.class: Tohouri\StoreBundle\Example

services:
#    tohouri_store.example:
#        class: %tohouri_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tohouri_store.registration.form.type:
        class: Tohouri\StoreBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: tohouri_user_registration }
