parameters:
#    tohouri_store.example.class: Tohouri\StoreBundle\Example

services:
#    tohouri_store.example:
#        class: %tohouri_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
