<?php

namespace Tohouri\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganisationUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisationUnitRepository extends EntityRepository
{
}